# Generated by Django 3.2.4 on 2021-08-27 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(default='static/images/prof.jpg', upload_to='static/images')),
                ('slug', models.SlugField(default='slug', editable=False)),
                ('gender', models.CharField(choices=[('Gen', 'Kisi'), ('Gen', 'Kadin'), ('Gen', 'Yeniyetme')], max_length=255, null=True)),
                ('facebook_hesabi', models.URLField(blank=True, max_length=255)),
                ('twitter_hesabi', models.URLField(blank=True, max_length=255)),
                ('linkedin_hesabi', models.URLField(blank=True, max_length=255)),
                ('youtube_hesabi', models.URLField(blank=True, max_length=255)),
                ('instaqram_hesabi', models.URLField(blank=True, max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='dostlar', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
