# Generated by Django 3.2.4 on 2021-08-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/images/prof.jpg', upload_to='users'),
        ),
    ]
