# Generated by Django 3.2.4 on 2021-08-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_yas'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='yasadigi_yer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
