# Generated by Django 3.2.4 on 2021-08-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_yasadigi_yer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='islediyi_yer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
