# Generated by Django 3.2.4 on 2021-09-04 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_profile_islediyi_yer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friends',
            new_name='avatnds',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='slug',
            new_name='frie',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='slugar',
        ),
    ]
