# Generated by Django 3.2.4 on 2021-09-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='resim',
        ),
    ]
