# Generated by Django 3.2.4 on 2021-09-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20210903_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='taglarimiz', to='article.Tag'),
        ),
    ]
