# Generated by Django 3.2.4 on 2021-09-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210919_1409'),
        ('article', '0020_rename_hit_post_post_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adam', to='account.profile'),
        ),
    ]
