# Generated by Django 3.2.4 on 2021-09-20 03:58

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sekil',
            field=models.ImageField(default='users/amk.jpg', upload_to='users', verbose_name=account.models.Profile),
        ),
    ]
