# Generated by Django 3.2.4 on 2021-09-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210919_1409'),
        ('article', '0023_alter_comment_sekil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(related_name='adam', to='account.Profile'),
        ),
    ]
